// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inclticnisqmlnkolwlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluY2x0aWNuaXNxbWxua29sd2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDE3MTUsImV4cCI6MjA1ODQ3NzcxNX0.z5AF_lORtEU0hmXr8oe-x4ldbe249e4sPgY6BJqv4XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);